apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: ismail-pod
  replicas: 2
  template:
    metadata:
      name: ismail-pod
      labels:
        app: ismail-pod
    spec:
      containers:
        - name: ismail-pod
          image: nginx

---

apiVersion: v1
kind: service
metadata:
  name: demo-svc
spec:
  type: Nodeport
  selector:
    app: ismail-pod
  ports:
    - name: http
      port: 80
      targetPorts: 30000
      
---

apiVersion: v1
kind: service
metadata:
  name: clusterip-svc
spec:
  selector:
    app: ismail-pod
  ports:
    - name: http
      port: 80